"""Regenerate the small RAG measurements used in readings, labs, and slides.

Uses the provided chunker, embedder, exact index, and labeled questions.
Student TODOs remain untouched. No model, API, or network access is needed.
Run with --check to detect stale teaching data after changing the corpus/code.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
STARTER = ROOT / "labs/lab-10/starter"
OUTPUT = ROOT / "labs/_shared/rag-measurements.js"


def measurements():
    sys.path.insert(0, str(STARTER))
    import micro_rag
    from corpus import DOCS, EVAL
    from microvector import BruteForceIndex

    def evaluate(chunks):
        index = BruteForceIndex([micro_rag.embed(c["text"]) for c in chunks])
        hits, reciprocal_ranks = 0, 0.0
        for question, relevant in EVAL:
            result = index.search(micro_rag.embed(question), 3)
            ranks = [rank for rank, (_, i) in enumerate(result, 1)
                     if chunks[i]["doc"] in relevant]
            if ranks:
                hits += 1
                reciprocal_ranks += 1 / ranks[0]
        return {"chunks": len(chunks), "hit3": hits / len(EVAL),
                "mrr3": reciprocal_ranks / len(EVAL)}

    result = {
        "documents": len(DOCS), "questions": len(EVAL), "cutoff": 3,
        "inputs": {name: hashlib.sha256((STARTER / name).read_bytes()).hexdigest()
                   for name in ("corpus.py", "micro_rag.py", "microvector.py")},
        "width": [], "chunking": [],
        "preview": {"chunks": micro_rag.chunk_corpus(),
                    "stop": sorted(micro_rag.STOPWORDS),
                    "eval": [[question, sorted(relevant)] for question, relevant in EVAL]},
    }
    original_dim = micro_rag.DIM
    try:
        for dim in (64, 128, 256, 512, 1024, 2048, 4096):
            micro_rag.DIM = dim
            result["width"].append({"dim": dim, **evaluate(micro_rag.chunk_corpus())})
        micro_rag.DIM = 2048
        for target in (10, 20, 30, 45, 60, 90):
            result["chunking"].append({"max_words": target,
                                      **evaluate(micro_rag.chunk_corpus(target))})
    finally:
        micro_rag.DIM = original_dim
        sys.path.remove(str(STARTER))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.dumps(measurements(), indent=2, ensure_ascii=False)
    content = ("// Generated by scripts/generate_rag_measurements.py. Do not edit by hand.\n"
               "(function(root,data){if(typeof module==='object'&&module.exports)module.exports=data;"
               "else root.CourseRagMeasurements=data;})(typeof window==='undefined'?globalThis:window,\n"
               + data + ");\n")
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit("RAG teaching data is stale. Run scripts/generate_rag_measurements.py")
        print("RAG measurements match the current corpus, embedder, and exact index.")
    else:
        OUTPUT.write_text(content)
        print(OUTPUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
